name: Bad Buddhist
favicon: null
layout_spectrum: 0.24339
typography_spectrum: 0.49955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#180d15'
    - '#c6c3b0'
    - '#9b9d90'
    - '#4e4f53'
    - '#f3efc6'
  brandStrength: 0
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
